<a href="https://colab.research.google.com/github/PeaceOfGod/Hamoye-Practice-Exercises/blob/master/Lesson2%20(Numpy%20Array%20%26%20Vectorization)%20-%20Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import Numpy

In [15]:
import numpy as np

In [16]:
arr = np.array([[2,3,4], [5,6,7], [8,9,1]])

In [17]:
print (arr)

[[2 3 4]
 [5 6 7]
 [8 9 1]]


In [18]:
print (arr.dtype)

int64


In [19]:
print (arr.shape)

(3, 3)


In [20]:
print (arr.ndim)

2


In [21]:
b = np.array([[1,2], [2,3], [3,4], [4,5], [5,6]], float)
print ("Array Dimension is ", b.ndim)
print ("The shape of the array is ", b.shape)
print ("The array has a type: ", b.dtype)

Array Dimension is  2
The shape of the array is  (5, 2)
The array has a type:  float64


In [22]:
c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])

In [23]:
print (c + d)

[[13. 13. 13.]
 [10. 10. 10.]]


In [24]:
print (c * d)

[[36. 40. 42.]
 [ 9. 16. 21.]]


In [25]:
print ( 5  / d)

[[1.25       1.         0.83333333]
 [0.55555556 0.625      0.71428571]]


In [27]:
ask = c ** 2
print (ask)

[[81. 64. 49.]
 [ 1.  4.  9.]]


In [28]:
print (ask.dtype)
print (ask.ndim)
print (ask.size)
print (ask.shape)

float64
2
6
(2, 3)


##Indexing with arrays 

In [33]:
print (ask[1])
print (b[3])
print (b[-2])
print (ask[1][2])
print (c[0][2])

[1. 4. 9.]
[4. 5.]
[4. 5.]
9.0
7.0


##Slicing 

In [38]:
#ask[1, 0:1]
#ask[1, 0:2]
#ask[1, 0:3]
d[0, 0:2]

array([4., 5.])

In [39]:
e = np.array([[10, 11, 12], [13, 14, 15],
              [16, 17, 18], [19, 20, 21]])

In [40]:
e[:3, :2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [41]:
e[[2, 0, 3, 1], [2, 1, 0, 2]]

array([18, 11, 19, 15])

In [42]:
e[e>15]

array([16, 17, 18, 19, 20, 21])

In [43]:
b[[1, 3, 4, 0], [0, 1, 1, 0]]

array([2., 5., 6., 1.])